package com.eivencrm.entity;
// Generated 2017-12-14 10:40:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MkUser generated by hbm2java
 */
@Entity
@Table(name = "mk_user", catalog = "eivencrm")
public class MkUser implements java.io.Serializable {

	private String id;
	private String userName;
	private String nickName;
	private String realName;
	private String mobile;
	private String email;
	private String password;
	private String skill;
	private Integer sex;
	private Integer birthday;
	private Integer age;
	private String shuoMing;
	private String portraitUrl;
	private String comment;
	private String qrcode;
	private String wxid;
	private Integer wxSubs;
	private String imid;
	private String impwd;
	private Integer idAuthStatus;
	private Integer mobileAuthStatus;
	private Integer emailAuthStatus;
	private String country;
	private String province;
	private String city;
	private String area;
	private String roles;
	private Integer payStatus;
	private String unionid;
	private String lang;
	private Integer status;
	private Long leader;
	private Integer lastLogTime;
	private Long userLevel;
	private BigDecimal userScore;
	private Byte deleted;
	private Integer recommend;
	private String integrationRule;
	private Integer perfectInfo;
	private String creator;
	private Integer createTime;
	private String updator;
	private Integer updateTime;
	private Long orgId;
	private long shopId;
	private Integer contribution;

	public MkUser() {
	}

	public MkUser(String id, long shopId) {
		this.id = id;
		this.shopId = shopId;
	}

	public MkUser(String id, String userName, String nickName, String realName, String mobile, String email,
			String password, String skill, Integer sex, Integer birthday, Integer age, String shuoMing,
			String portraitUrl, String comment, String qrcode, String wxid, Integer wxSubs, String imid, String impwd,
			Integer idAuthStatus, Integer mobileAuthStatus, Integer emailAuthStatus, String country, String province,
			String city, String area, String roles, Integer payStatus, String unionid, String lang, Integer status,
			Long leader, Integer lastLogTime, Long userLevel, BigDecimal userScore, Byte deleted, Integer recommend,
			String integrationRule, Integer perfectInfo, String creator, Integer createTime, String updator,
			Integer updateTime, Long orgId, long shopId, Integer contribution) {
		this.id = id;
		this.userName = userName;
		this.nickName = nickName;
		this.realName = realName;
		this.mobile = mobile;
		this.email = email;
		this.password = password;
		this.skill = skill;
		this.sex = sex;
		this.birthday = birthday;
		this.age = age;
		this.shuoMing = shuoMing;
		this.portraitUrl = portraitUrl;
		this.comment = comment;
		this.qrcode = qrcode;
		this.wxid = wxid;
		this.wxSubs = wxSubs;
		this.imid = imid;
		this.impwd = impwd;
		this.idAuthStatus = idAuthStatus;
		this.mobileAuthStatus = mobileAuthStatus;
		this.emailAuthStatus = emailAuthStatus;
		this.country = country;
		this.province = province;
		this.city = city;
		this.area = area;
		this.roles = roles;
		this.payStatus = payStatus;
		this.unionid = unionid;
		this.lang = lang;
		this.status = status;
		this.leader = leader;
		this.lastLogTime = lastLogTime;
		this.userLevel = userLevel;
		this.userScore = userScore;
		this.deleted = deleted;
		this.recommend = recommend;
		this.integrationRule = integrationRule;
		this.perfectInfo = perfectInfo;
		this.creator = creator;
		this.createTime = createTime;
		this.updator = updator;
		this.updateTime = updateTime;
		this.orgId = orgId;
		this.shopId = shopId;
		this.contribution = contribution;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 18)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "user_name")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "nick_name")
	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	@Column(name = "real_name")
	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	@Column(name = "mobile")
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "skill")
	public String getSkill() {
		return this.skill;
	}

	public void setSkill(String skill) {
		this.skill = skill;
	}

	@Column(name = "sex")
	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	@Column(name = "birthday")
	public Integer getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Integer birthday) {
		this.birthday = birthday;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "shuo_ming")
	public String getShuoMing() {
		return this.shuoMing;
	}

	public void setShuoMing(String shuoMing) {
		this.shuoMing = shuoMing;
	}

	@Column(name = "portrait_url")
	public String getPortraitUrl() {
		return this.portraitUrl;
	}

	public void setPortraitUrl(String portraitUrl) {
		this.portraitUrl = portraitUrl;
	}

	@Column(name = "comment")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "qrcode")
	public String getQrcode() {
		return this.qrcode;
	}

	public void setQrcode(String qrcode) {
		this.qrcode = qrcode;
	}

	@Column(name = "wxid")
	public String getWxid() {
		return this.wxid;
	}

	public void setWxid(String wxid) {
		this.wxid = wxid;
	}

	@Column(name = "wx_subs")
	public Integer getWxSubs() {
		return this.wxSubs;
	}

	public void setWxSubs(Integer wxSubs) {
		this.wxSubs = wxSubs;
	}

	@Column(name = "imid")
	public String getImid() {
		return this.imid;
	}

	public void setImid(String imid) {
		this.imid = imid;
	}

	@Column(name = "impwd")
	public String getImpwd() {
		return this.impwd;
	}

	public void setImpwd(String impwd) {
		this.impwd = impwd;
	}

	@Column(name = "id_auth_status")
	public Integer getIdAuthStatus() {
		return this.idAuthStatus;
	}

	public void setIdAuthStatus(Integer idAuthStatus) {
		this.idAuthStatus = idAuthStatus;
	}

	@Column(name = "mobile_auth_status")
	public Integer getMobileAuthStatus() {
		return this.mobileAuthStatus;
	}

	public void setMobileAuthStatus(Integer mobileAuthStatus) {
		this.mobileAuthStatus = mobileAuthStatus;
	}

	@Column(name = "email_auth_status")
	public Integer getEmailAuthStatus() {
		return this.emailAuthStatus;
	}

	public void setEmailAuthStatus(Integer emailAuthStatus) {
		this.emailAuthStatus = emailAuthStatus;
	}

	@Column(name = "country")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "province")
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "city")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "area")
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "roles")
	public String getRoles() {
		return this.roles;
	}

	public void setRoles(String roles) {
		this.roles = roles;
	}

	@Column(name = "pay_status")
	public Integer getPayStatus() {
		return this.payStatus;
	}

	public void setPayStatus(Integer payStatus) {
		this.payStatus = payStatus;
	}

	@Column(name = "unionid")
	public String getUnionid() {
		return this.unionid;
	}

	public void setUnionid(String unionid) {
		this.unionid = unionid;
	}

	@Column(name = "lang")
	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "leader")
	public Long getLeader() {
		return this.leader;
	}

	public void setLeader(Long leader) {
		this.leader = leader;
	}

	@Column(name = "last_log_time")
	public Integer getLastLogTime() {
		return this.lastLogTime;
	}

	public void setLastLogTime(Integer lastLogTime) {
		this.lastLogTime = lastLogTime;
	}

	@Column(name = "user_level")
	public Long getUserLevel() {
		return this.userLevel;
	}

	public void setUserLevel(Long userLevel) {
		this.userLevel = userLevel;
	}

	@Column(name = "user_score", precision = 10)
	public BigDecimal getUserScore() {
		return this.userScore;
	}

	public void setUserScore(BigDecimal userScore) {
		this.userScore = userScore;
	}

	@Column(name = "deleted")
	public Byte getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Byte deleted) {
		this.deleted = deleted;
	}

	@Column(name = "recommend")
	public Integer getRecommend() {
		return this.recommend;
	}

	public void setRecommend(Integer recommend) {
		this.recommend = recommend;
	}

	@Column(name = "integration_rule", length = 65535)
	public String getIntegrationRule() {
		return this.integrationRule;
	}

	public void setIntegrationRule(String integrationRule) {
		this.integrationRule = integrationRule;
	}

	@Column(name = "perfect_info")
	public Integer getPerfectInfo() {
		return this.perfectInfo;
	}

	public void setPerfectInfo(Integer perfectInfo) {
		this.perfectInfo = perfectInfo;
	}

	@Column(name = "creator")
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "create_time")
	public Integer getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Integer createTime) {
		this.createTime = createTime;
	}

	@Column(name = "updator")
	public String getUpdator() {
		return this.updator;
	}

	public void setUpdator(String updator) {
		this.updator = updator;
	}

	@Column(name = "update_time")
	public Integer getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Integer updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "org_id")
	public Long getOrgId() {
		return this.orgId;
	}

	public void setOrgId(Long orgId) {
		this.orgId = orgId;
	}

	@Column(name = "shop_id", nullable = false)
	public long getShopId() {
		return this.shopId;
	}

	public void setShopId(long shopId) {
		this.shopId = shopId;
	}

	@Column(name = "contribution")
	public Integer getContribution() {
		return this.contribution;
	}

	public void setContribution(Integer contribution) {
		this.contribution = contribution;
	}

}
